"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.file_walletrpc_walletkit = exports.WitnessTypeSchema = exports.WitnessType = exports.WalletKit = exports.VerifyMessageWithAddrResponseSchema = exports.VerifyMessageWithAddrRequestSchema = exports.UtxoLeaseSchema = exports.TxTemplateSchema = exports.TransactionSchema = exports.TapscriptPartialRevealSchema = exports.TapscriptFullTreeSchema = exports.TapLeafSchema = exports.SignPsbtResponseSchema = exports.SignPsbtRequestSchema = exports.SignMessageWithAddrResponseSchema = exports.SignMessageWithAddrRequestSchema = exports.SendOutputsResponseSchema = exports.SendOutputsRequestSchema = exports.RequiredReserveResponseSchema = exports.RequiredReserveRequestSchema = exports.ReleaseOutputResponseSchema = exports.ReleaseOutputRequestSchema = exports.PublishResponseSchema = exports.PendingSweepsResponseSchema = exports.PendingSweepsRequestSchema = exports.PendingSweepSchema = exports.ListUnspentResponseSchema = exports.ListUnspentRequestSchema = exports.ListSweepsResponse_TransactionIDsSchema = exports.ListSweepsResponseSchema = exports.ListSweepsRequestSchema = exports.ListLeasesResponseSchema = exports.ListLeasesRequestSchema = exports.ListAddressesResponseSchema = exports.ListAddressesRequestSchema = exports.ListAccountsResponseSchema = exports.ListAccountsRequestSchema = exports.LeaseOutputResponseSchema = exports.LeaseOutputRequestSchema = exports.LabelTransactionResponseSchema = exports.LabelTransactionRequestSchema = exports.KeyReqSchema = exports.ImportTapscriptResponseSchema = exports.ImportTapscriptRequestSchema = exports.ImportPublicKeyResponseSchema = exports.ImportPublicKeyRequestSchema = exports.ImportAccountResponseSchema = exports.ImportAccountRequestSchema = exports.FundPsbtResponseSchema = exports.FundPsbtRequestSchema = exports.FinalizePsbtResponseSchema = exports.FinalizePsbtRequestSchema = exports.EstimateFeeResponseSchema = exports.EstimateFeeRequestSchema = exports.ChangeAddressTypeSchema = exports.ChangeAddressType = exports.BumpFeeResponseSchema = exports.BumpFeeRequestSchema = exports.AddressTypeSchema = exports.AddressType = exports.AddressPropertySchema = exports.AddrResponseSchema = exports.AddrRequestSchema = exports.AccountWithAddressesSchema = exports.AccountSchema = void 0;
var _codegenv = require("@bufbuild/protobuf/codegenv2");
var _lightning_pb = require("../lightning_pb.js");
var _signer_pb = require("../signrpc/signer_pb.js");
// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file walletrpc/walletkit.proto (package walletrpc, syntax proto3)
/* eslint-disable */

/**
 * Describes the file walletrpc/walletkit.proto.
 */
const file_walletrpc_walletkit = exports.file_walletrpc_walletkit = /*@__PURE__*/
(0, _codegenv.fileDesc)("Chl3YWxsZXRycGMvd2FsbGV0a2l0LnByb3RvEgl3YWxsZXRycGMiZQoSTGlzdFVuc3BlbnRSZXF1ZXN0EhEKCW1pbl9jb25mcxgBIAEoBRIRCgltYXhfY29uZnMYAiABKAUSDwoHYWNjb3VudBgDIAEoCRIYChB1bmNvbmZpcm1lZF9vbmx5GAQgASgIIjEKE0xpc3RVbnNwZW50UmVzcG9uc2USGgoFdXR4b3MYASADKAsyCy5sbnJwYy5VdHhvIl8KEkxlYXNlT3V0cHV0UmVxdWVzdBIKCgJpZBgBIAEoDBIhCghvdXRwb2ludBgCIAEoCzIPLmxucnBjLk91dFBvaW50EhoKEmV4cGlyYXRpb25fc2Vjb25kcxgDIAEoBCIpChNMZWFzZU91dHB1dFJlc3BvbnNlEhIKCmV4cGlyYXRpb24YASABKAQiRQoUUmVsZWFzZU91dHB1dFJlcXVlc3QSCgoCaWQYASABKAwSIQoIb3V0cG9pbnQYAiABKAsyDy5sbnJwYy5PdXRQb2ludCIXChVSZWxlYXNlT3V0cHV0UmVzcG9uc2UiNgoGS2V5UmVxEhgKEGtleV9maW5nZXJfcHJpbnQYASABKAUSEgoKa2V5X2ZhbWlseRgCIAEoBSJUCgtBZGRyUmVxdWVzdBIPCgdhY2NvdW50GAEgASgJEiQKBHR5cGUYAiABKA4yFi53YWxsZXRycGMuQWRkcmVzc1R5cGUSDgoGY2hhbmdlGAMgASgIIhwKDEFkZHJSZXNwb25zZRIMCgRhZGRyGAEgASgJIucBCgdBY2NvdW50EgwKBG5hbWUYASABKAkSLAoMYWRkcmVzc190eXBlGAIgASgOMhYud2FsbGV0cnBjLkFkZHJlc3NUeXBlEhsKE2V4dGVuZGVkX3B1YmxpY19rZXkYAyABKAkSHgoWbWFzdGVyX2tleV9maW5nZXJwcmludBgEIAEoDBIXCg9kZXJpdmF0aW9uX3BhdGgYBSABKAkSGgoSZXh0ZXJuYWxfa2V5X2NvdW50GAYgASgNEhoKEmludGVybmFsX2tleV9jb3VudBgHIAEoDRISCgp3YXRjaF9vbmx5GAggASgIIkgKD0FkZHJlc3NQcm9wZXJ0eRIPCgdhZGRyZXNzGAEgASgJEhMKC2lzX2ludGVybmFsGAIgASgIEg8KB2JhbGFuY2UYAyABKAMimgEKFEFjY291bnRXaXRoQWRkcmVzc2VzEgwKBG5hbWUYASABKAkSLAoMYWRkcmVzc190eXBlGAIgASgOMhYud2FsbGV0cnBjLkFkZHJlc3NUeXBlEhcKD2Rlcml2YXRpb25fcGF0aBgDIAEoCRItCglhZGRyZXNzZXMYBCADKAsyGi53YWxsZXRycGMuQWRkcmVzc1Byb3BlcnR5IlEKE0xpc3RBY2NvdW50c1JlcXVlc3QSDAoEbmFtZRgBIAEoCRIsCgxhZGRyZXNzX3R5cGUYAiABKA4yFi53YWxsZXRycGMuQWRkcmVzc1R5cGUiPAoUTGlzdEFjY291bnRzUmVzcG9uc2USJAoIYWNjb3VudHMYASADKAsyEi53YWxsZXRycGMuQWNjb3VudCI8ChZSZXF1aXJlZFJlc2VydmVSZXF1ZXN0EiIKGmFkZGl0aW9uYWxfcHVibGljX2NoYW5uZWxzGAEgASgNIjMKF1JlcXVpcmVkUmVzZXJ2ZVJlc3BvbnNlEhgKEHJlcXVpcmVkX3Jlc2VydmUYASABKAMiSgoUTGlzdEFkZHJlc3Nlc1JlcXVlc3QSFAoMYWNjb3VudF9uYW1lGAEgASgJEhwKFHNob3dfY3VzdG9tX2FjY291bnRzGAIgASgIIlgKFUxpc3RBZGRyZXNzZXNSZXNwb25zZRI/ChZhY2NvdW50X3dpdGhfYWRkcmVzc2VzGAEgAygLMh8ud2FsbGV0cnBjLkFjY291bnRXaXRoQWRkcmVzc2VzIjcKGlNpZ25NZXNzYWdlV2l0aEFkZHJSZXF1ZXN0EgsKA21zZxgBIAEoDBIMCgRhZGRyGAIgASgJIjAKG1NpZ25NZXNzYWdlV2l0aEFkZHJSZXNwb25zZRIRCglzaWduYXR1cmUYASABKAkiTAocVmVyaWZ5TWVzc2FnZVdpdGhBZGRyUmVxdWVzdBILCgNtc2cYASABKAwSEQoJc2lnbmF0dXJlGAIgASgJEgwKBGFkZHIYAyABKAkiPgodVmVyaWZ5TWVzc2FnZVdpdGhBZGRyUmVzcG9uc2USDQoFdmFsaWQYASABKAgSDgoGcHVia2V5GAIgASgMIqABChRJbXBvcnRBY2NvdW50UmVxdWVzdBIMCgRuYW1lGAEgASgJEhsKE2V4dGVuZGVkX3B1YmxpY19rZXkYAiABKAkSHgoWbWFzdGVyX2tleV9maW5nZXJwcmludBgDIAEoDBIsCgxhZGRyZXNzX3R5cGUYBCABKA4yFi53YWxsZXRycGMuQWRkcmVzc1R5cGUSDwoHZHJ5X3J1bhgFIAEoCCJ8ChVJbXBvcnRBY2NvdW50UmVzcG9uc2USIwoHYWNjb3VudBgBIAEoCzISLndhbGxldHJwYy5BY2NvdW50Eh4KFmRyeV9ydW5fZXh0ZXJuYWxfYWRkcnMYAiADKAkSHgoWZHJ5X3J1bl9pbnRlcm5hbF9hZGRycxgDIAMoCSJaChZJbXBvcnRQdWJsaWNLZXlSZXF1ZXN0EhIKCnB1YmxpY19rZXkYASABKAwSLAoMYWRkcmVzc190eXBlGAIgASgOMhYud2FsbGV0cnBjLkFkZHJlc3NUeXBlIhkKF0ltcG9ydFB1YmxpY0tleVJlc3BvbnNlIuIBChZJbXBvcnRUYXBzY3JpcHRSZXF1ZXN0EhsKE2ludGVybmFsX3B1YmxpY19rZXkYASABKAwSMQoJZnVsbF90cmVlGAIgASgLMhwud2FsbGV0cnBjLlRhcHNjcmlwdEZ1bGxUcmVlSAASOwoOcGFydGlhbF9yZXZlYWwYAyABKAsyIS53YWxsZXRycGMuVGFwc2NyaXB0UGFydGlhbFJldmVhbEgAEhgKDnJvb3RfaGFzaF9vbmx5GAQgASgMSAASFwoNZnVsbF9rZXlfb25seRgFIAEoCEgAQggKBnNjcmlwdCI7ChFUYXBzY3JpcHRGdWxsVHJlZRImCgphbGxfbGVhdmVzGAEgAygLMhIud2FsbGV0cnBjLlRhcExlYWYiLwoHVGFwTGVhZhIUCgxsZWFmX3ZlcnNpb24YASABKA0SDgoGc2NyaXB0GAIgASgMImEKFlRhcHNjcmlwdFBhcnRpYWxSZXZlYWwSKQoNcmV2ZWFsZWRfbGVhZhgBIAEoCzISLndhbGxldHJwYy5UYXBMZWFmEhwKFGZ1bGxfaW5jbHVzaW9uX3Byb29mGAIgASgMIi8KF0ltcG9ydFRhcHNjcmlwdFJlc3BvbnNlEhQKDHAydHJfYWRkcmVzcxgBIAEoCSIsCgtUcmFuc2FjdGlvbhIOCgZ0eF9oZXgYASABKAwSDQoFbGFiZWwYAiABKAkiKAoPUHVibGlzaFJlc3BvbnNlEhUKDXB1Ymxpc2hfZXJyb3IYASABKAkihgEKElNlbmRPdXRwdXRzUmVxdWVzdBISCgpzYXRfcGVyX2t3GAEgASgDEh8KB291dHB1dHMYAiADKAsyDi5zaWducnBjLlR4T3V0Eg0KBWxhYmVsGAMgASgJEhEKCW1pbl9jb25mcxgEIAEoBRIZChFzcGVuZF91bmNvbmZpcm1lZBgFIAEoCCIlChNTZW5kT3V0cHV0c1Jlc3BvbnNlEg4KBnJhd190eBgBIAEoDCIpChJFc3RpbWF0ZUZlZVJlcXVlc3QSEwoLY29uZl90YXJnZXQYASABKAUiKQoTRXN0aW1hdGVGZWVSZXNwb25zZRISCgpzYXRfcGVyX2t3GAEgASgDItICCgxQZW5kaW5nU3dlZXASIQoIb3V0cG9pbnQYASABKAsyDy5sbnJwYy5PdXRQb2ludBIsCgx3aXRuZXNzX3R5cGUYAiABKA4yFi53YWxsZXRycGMuV2l0bmVzc1R5cGUSEgoKYW1vdW50X3NhdBgDIAEoDRIYCgxzYXRfcGVyX2J5dGUYBCABKA1CAhgBEhoKEmJyb2FkY2FzdF9hdHRlbXB0cxgFIAEoDRIdChVuZXh0X2Jyb2FkY2FzdF9oZWlnaHQYBiABKA0SHQoVcmVxdWVzdGVkX2NvbmZfdGFyZ2V0GAggASgNEiIKFnJlcXVlc3RlZF9zYXRfcGVyX2J5dGUYCSABKA1CAhgBEhUKDXNhdF9wZXJfdmJ5dGUYCiABKAQSHwoXcmVxdWVzdGVkX3NhdF9wZXJfdmJ5dGUYCyABKAQSDQoFZm9yY2UYByABKAgiFgoUUGVuZGluZ1N3ZWVwc1JlcXVlc3QiSAoVUGVuZGluZ1N3ZWVwc1Jlc3BvbnNlEi8KDnBlbmRpbmdfc3dlZXBzGAEgAygLMhcud2FsbGV0cnBjLlBlbmRpbmdTd2VlcCKIAQoOQnVtcEZlZVJlcXVlc3QSIQoIb3V0cG9pbnQYASABKAsyDy5sbnJwYy5PdXRQb2ludBITCgt0YXJnZXRfY29uZhgCIAEoDRIYCgxzYXRfcGVyX2J5dGUYAyABKA1CAhgBEg0KBWZvcmNlGAQgASgIEhUKDXNhdF9wZXJfdmJ5dGUYBSABKAQiEQoPQnVtcEZlZVJlc3BvbnNlIiQKEUxpc3RTd2VlcHNSZXF1ZXN0Eg8KB3ZlcmJvc2UYASABKAgizAEKEkxpc3RTd2VlcHNSZXNwb25zZRI4ChN0cmFuc2FjdGlvbl9kZXRhaWxzGAEgASgLMhkubG5ycGMuVHJhbnNhY3Rpb25EZXRhaWxzSAASRwoPdHJhbnNhY3Rpb25faWRzGAIgASgLMiwud2FsbGV0cnBjLkxpc3RTd2VlcHNSZXNwb25zZS5UcmFuc2FjdGlvbklEc0gAGikKDlRyYW5zYWN0aW9uSURzEhcKD3RyYW5zYWN0aW9uX2lkcxgBIAMoCUIICgZzd2VlcHMiSQoXTGFiZWxUcmFuc2FjdGlvblJlcXVlc3QSDAoEdHhpZBgBIAEoDBINCgVsYWJlbBgCIAEoCRIRCglvdmVyd3JpdGUYAyABKAgiGgoYTGFiZWxUcmFuc2FjdGlvblJlc3BvbnNlIv0BCg9GdW5kUHNidFJlcXVlc3QSDgoEcHNidBgBIAEoDEgAEiQKA3JhdxgCIAEoCzIVLndhbGxldHJwYy5UeFRlbXBsYXRlSAASFQoLdGFyZ2V0X2NvbmYYAyABKA1IARIXCg1zYXRfcGVyX3ZieXRlGAQgASgESAESDwoHYWNjb3VudBgFIAEoCRIRCgltaW5fY29uZnMYBiABKAUSGQoRc3BlbmRfdW5jb25maXJtZWQYByABKAgSMQoLY2hhbmdlX3R5cGUYCCABKA4yHC53YWxsZXRycGMuQ2hhbmdlQWRkcmVzc1R5cGVCCgoIdGVtcGxhdGVCBgoEZmVlcyJwChBGdW5kUHNidFJlc3BvbnNlEhMKC2Z1bmRlZF9wc2J0GAEgASgMEhsKE2NoYW5nZV9vdXRwdXRfaW5kZXgYAiABKAUSKgoMbG9ja2VkX3V0eG9zGAMgAygLMhQud2FsbGV0cnBjLlV0eG9MZWFzZSKRAQoKVHhUZW1wbGF0ZRIeCgZpbnB1dHMYASADKAsyDi5sbnJwYy5UeElucHV0EjMKB291dHB1dHMYAiADKAsyIi53YWxsZXRycGMuVHhUZW1wbGF0ZS5PdXRwdXRzRW50cnkaLgoMT3V0cHV0c0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoBDoCOAEicAoJVXR4b0xlYXNlEgoKAmlkGAEgASgMEiEKCG91dHBvaW50GAIgASgLMg8ubG5ycGMuT3V0UG9pbnQSEgoKZXhwaXJhdGlvbhgDIAEoBBIRCglwa19zY3JpcHQYBCABKAwSDQoFdmFsdWUYBSABKAQiJgoPU2lnblBzYnRSZXF1ZXN0EhMKC2Z1bmRlZF9wc2J0GAEgASgMIj4KEFNpZ25Qc2J0UmVzcG9uc2USEwoLc2lnbmVkX3BzYnQYASABKAwSFQoNc2lnbmVkX2lucHV0cxgCIAMoDSI7ChNGaW5hbGl6ZVBzYnRSZXF1ZXN0EhMKC2Z1bmRlZF9wc2J0GAEgASgMEg8KB2FjY291bnQYBSABKAkiQQoURmluYWxpemVQc2J0UmVzcG9uc2USEwoLc2lnbmVkX3BzYnQYASABKAwSFAoMcmF3X2ZpbmFsX3R4GAIgASgMIhMKEUxpc3RMZWFzZXNSZXF1ZXN0IkAKEkxpc3RMZWFzZXNSZXNwb25zZRIqCgxsb2NrZWRfdXR4b3MYASADKAsyFC53YWxsZXRycGMuVXR4b0xlYXNlKo4BCgtBZGRyZXNzVHlwZRILCgdVTktOT1dOEAASFwoTV0lUTkVTU19QVUJLRVlfSEFTSBABEh4KGk5FU1RFRF9XSVRORVNTX1BVQktFWV9IQVNIEAISJQohSFlCUklEX05FU1RFRF9XSVRORVNTX1BVQktFWV9IQVNIEAMSEgoOVEFQUk9PVF9QVUJLRVkQBCqPBgoLV2l0bmVzc1R5cGUSEwoPVU5LTk9XTl9XSVRORVNTEAASGAoUQ09NTUlUTUVOVF9USU1FX0xPQ0sQARIXChNDT01NSVRNRU5UX05PX0RFTEFZEAISFQoRQ09NTUlUTUVOVF9SRVZPS0UQAxIXChNIVExDX09GRkVSRURfUkVWT0tFEAQSGAoUSFRMQ19BQ0NFUFRFRF9SRVZPS0UQBRIlCiFIVExDX09GRkVSRURfVElNRU9VVF9TRUNPTkRfTEVWRUwQBhImCiJIVExDX0FDQ0VQVEVEX1NVQ0NFU1NfU0VDT05EX0xFVkVMEAcSHwobSFRMQ19PRkZFUkVEX1JFTU9URV9USU1FT1VUEAgSIAocSFRMQ19BQ0NFUFRFRF9SRU1PVEVfU1VDQ0VTUxAJEhwKGEhUTENfU0VDT05EX0xFVkVMX1JFVk9LRRAKEhQKEFdJVE5FU1NfS0VZX0hBU0gQCxIbChdORVNURURfV0lUTkVTU19LRVlfSEFTSBAMEhUKEUNPTU1JVE1FTlRfQU5DSE9SEA0SIQodQ09NTUlUTUVOVF9OT19ERUxBWV9UV0VBS0xFU1MQDhIiCh5DT01NSVRNRU5UX1RPX1JFTU9URV9DT05GSVJNRUQQDxI1CjFIVExDX09GRkVSRURfVElNRU9VVF9TRUNPTkRfTEVWRUxfSU5QVVRfQ09ORklSTUVEEBASNgoySFRMQ19BQ0NFUFRFRF9TVUNDRVNTX1NFQ09ORF9MRVZFTF9JTlBVVF9DT05GSVJNRUQQERIeChpMRUFTRV9DT01NSVRNRU5UX1RJTUVfTE9DSxASEigKJExFQVNFX0NPTU1JVE1FTlRfVE9fUkVNT1RFX0NPTkZJUk1FRBATEisKJ0xFQVNFX0hUTENfT0ZGRVJFRF9USU1FT1VUX1NFQ09ORF9MRVZFTBAUEiwKKExFQVNFX0hUTENfQUNDRVBURURfU1VDQ0VTU19TRUNPTkRfTEVWRUwQFRIZChVUQVBST09UX1BVQl9LRVlfU1BFTkQQFip0ChFDaGFuZ2VBZGRyZXNzVHlwZRIjCh9DSEFOR0VfQUREUkVTU19UWVBFX1VOU1BFQ0lGSUVEEAASHAoYQ0hBTkdFX0FERFJFU1NfVFlQRV9QMlRSEAESHAoYQ0hBTkdFX0FERFJFU1NfVFlQRV9NV0VCEAIy0Q8KCVdhbGxldEtpdBJMCgtMaXN0VW5zcGVudBIdLndhbGxldHJwYy5MaXN0VW5zcGVudFJlcXVlc3QaHi53YWxsZXRycGMuTGlzdFVuc3BlbnRSZXNwb25zZRJMCgtMZWFzZU91dHB1dBIdLndhbGxldHJwYy5MZWFzZU91dHB1dFJlcXVlc3QaHi53YWxsZXRycGMuTGVhc2VPdXRwdXRSZXNwb25zZRJSCg1SZWxlYXNlT3V0cHV0Eh8ud2FsbGV0cnBjLlJlbGVhc2VPdXRwdXRSZXF1ZXN0GiAud2FsbGV0cnBjLlJlbGVhc2VPdXRwdXRSZXNwb25zZRJJCgpMaXN0TGVhc2VzEhwud2FsbGV0cnBjLkxpc3RMZWFzZXNSZXF1ZXN0Gh0ud2FsbGV0cnBjLkxpc3RMZWFzZXNSZXNwb25zZRI6Cg1EZXJpdmVOZXh0S2V5EhEud2FsbGV0cnBjLktleVJlcRoWLnNpZ25ycGMuS2V5RGVzY3JpcHRvchI4CglEZXJpdmVLZXkSEy5zaWducnBjLktleUxvY2F0b3IaFi5zaWducnBjLktleURlc2NyaXB0b3ISOwoITmV4dEFkZHISFi53YWxsZXRycGMuQWRkclJlcXVlc3QaFy53YWxsZXRycGMuQWRkclJlc3BvbnNlEk8KDExpc3RBY2NvdW50cxIeLndhbGxldHJwYy5MaXN0QWNjb3VudHNSZXF1ZXN0Gh8ud2FsbGV0cnBjLkxpc3RBY2NvdW50c1Jlc3BvbnNlElgKD1JlcXVpcmVkUmVzZXJ2ZRIhLndhbGxldHJwYy5SZXF1aXJlZFJlc2VydmVSZXF1ZXN0GiIud2FsbGV0cnBjLlJlcXVpcmVkUmVzZXJ2ZVJlc3BvbnNlElIKDUxpc3RBZGRyZXNzZXMSHy53YWxsZXRycGMuTGlzdEFkZHJlc3Nlc1JlcXVlc3QaIC53YWxsZXRycGMuTGlzdEFkZHJlc3Nlc1Jlc3BvbnNlEmQKE1NpZ25NZXNzYWdlV2l0aEFkZHISJS53YWxsZXRycGMuU2lnbk1lc3NhZ2VXaXRoQWRkclJlcXVlc3QaJi53YWxsZXRycGMuU2lnbk1lc3NhZ2VXaXRoQWRkclJlc3BvbnNlEmoKFVZlcmlmeU1lc3NhZ2VXaXRoQWRkchInLndhbGxldHJwYy5WZXJpZnlNZXNzYWdlV2l0aEFkZHJSZXF1ZXN0Gigud2FsbGV0cnBjLlZlcmlmeU1lc3NhZ2VXaXRoQWRkclJlc3BvbnNlElIKDUltcG9ydEFjY291bnQSHy53YWxsZXRycGMuSW1wb3J0QWNjb3VudFJlcXVlc3QaIC53YWxsZXRycGMuSW1wb3J0QWNjb3VudFJlc3BvbnNlElgKD0ltcG9ydFB1YmxpY0tleRIhLndhbGxldHJwYy5JbXBvcnRQdWJsaWNLZXlSZXF1ZXN0GiIud2FsbGV0cnBjLkltcG9ydFB1YmxpY0tleVJlc3BvbnNlElgKD0ltcG9ydFRhcHNjcmlwdBIhLndhbGxldHJwYy5JbXBvcnRUYXBzY3JpcHRSZXF1ZXN0GiIud2FsbGV0cnBjLkltcG9ydFRhcHNjcmlwdFJlc3BvbnNlEkgKElB1Ymxpc2hUcmFuc2FjdGlvbhIWLndhbGxldHJwYy5UcmFuc2FjdGlvbhoaLndhbGxldHJwYy5QdWJsaXNoUmVzcG9uc2USTAoLU2VuZE91dHB1dHMSHS53YWxsZXRycGMuU2VuZE91dHB1dHNSZXF1ZXN0Gh4ud2FsbGV0cnBjLlNlbmRPdXRwdXRzUmVzcG9uc2USTAoLRXN0aW1hdGVGZWUSHS53YWxsZXRycGMuRXN0aW1hdGVGZWVSZXF1ZXN0Gh4ud2FsbGV0cnBjLkVzdGltYXRlRmVlUmVzcG9uc2USUgoNUGVuZGluZ1N3ZWVwcxIfLndhbGxldHJwYy5QZW5kaW5nU3dlZXBzUmVxdWVzdBogLndhbGxldHJwYy5QZW5kaW5nU3dlZXBzUmVzcG9uc2USQAoHQnVtcEZlZRIZLndhbGxldHJwYy5CdW1wRmVlUmVxdWVzdBoaLndhbGxldHJwYy5CdW1wRmVlUmVzcG9uc2USSQoKTGlzdFN3ZWVwcxIcLndhbGxldHJwYy5MaXN0U3dlZXBzUmVxdWVzdBodLndhbGxldHJwYy5MaXN0U3dlZXBzUmVzcG9uc2USWwoQTGFiZWxUcmFuc2FjdGlvbhIiLndhbGxldHJwYy5MYWJlbFRyYW5zYWN0aW9uUmVxdWVzdBojLndhbGxldHJwYy5MYWJlbFRyYW5zYWN0aW9uUmVzcG9uc2USQwoIRnVuZFBzYnQSGi53YWxsZXRycGMuRnVuZFBzYnRSZXF1ZXN0Ghsud2FsbGV0cnBjLkZ1bmRQc2J0UmVzcG9uc2USQwoIU2lnblBzYnQSGi53YWxsZXRycGMuU2lnblBzYnRSZXF1ZXN0Ghsud2FsbGV0cnBjLlNpZ25Qc2J0UmVzcG9uc2USTwoMRmluYWxpemVQc2J0Eh4ud2FsbGV0cnBjLkZpbmFsaXplUHNidFJlcXVlc3QaHy53YWxsZXRycGMuRmluYWxpemVQc2J0UmVzcG9uc2VCKVonZ2l0aHViLmNvbS9sdGNzdWl0ZS9sbmQvbG5ycGMvd2FsbGV0cnBjYgZwcm90bzM", [_lightning_pb.file_lightning, _signer_pb.file_signrpc_signer]);

/**
 * @generated from message walletrpc.ListUnspentRequest
 */

/**
 * Describes the message walletrpc.ListUnspentRequest.
 * Use `create(ListUnspentRequestSchema)` to create a new message.
 */
const ListUnspentRequestSchema = exports.ListUnspentRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 0);

/**
 * @generated from message walletrpc.ListUnspentResponse
 */

/**
 * Describes the message walletrpc.ListUnspentResponse.
 * Use `create(ListUnspentResponseSchema)` to create a new message.
 */
const ListUnspentResponseSchema = exports.ListUnspentResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 1);

/**
 * @generated from message walletrpc.LeaseOutputRequest
 */

/**
 * Describes the message walletrpc.LeaseOutputRequest.
 * Use `create(LeaseOutputRequestSchema)` to create a new message.
 */
const LeaseOutputRequestSchema = exports.LeaseOutputRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 2);

/**
 * @generated from message walletrpc.LeaseOutputResponse
 */

/**
 * Describes the message walletrpc.LeaseOutputResponse.
 * Use `create(LeaseOutputResponseSchema)` to create a new message.
 */
const LeaseOutputResponseSchema = exports.LeaseOutputResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 3);

/**
 * @generated from message walletrpc.ReleaseOutputRequest
 */

/**
 * Describes the message walletrpc.ReleaseOutputRequest.
 * Use `create(ReleaseOutputRequestSchema)` to create a new message.
 */
const ReleaseOutputRequestSchema = exports.ReleaseOutputRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 4);

/**
 * @generated from message walletrpc.ReleaseOutputResponse
 */

/**
 * Describes the message walletrpc.ReleaseOutputResponse.
 * Use `create(ReleaseOutputResponseSchema)` to create a new message.
 */
const ReleaseOutputResponseSchema = exports.ReleaseOutputResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 5);

/**
 * @generated from message walletrpc.KeyReq
 */

/**
 * Describes the message walletrpc.KeyReq.
 * Use `create(KeyReqSchema)` to create a new message.
 */
const KeyReqSchema = exports.KeyReqSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 6);

/**
 * @generated from message walletrpc.AddrRequest
 */

/**
 * Describes the message walletrpc.AddrRequest.
 * Use `create(AddrRequestSchema)` to create a new message.
 */
const AddrRequestSchema = exports.AddrRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 7);

/**
 * @generated from message walletrpc.AddrResponse
 */

/**
 * Describes the message walletrpc.AddrResponse.
 * Use `create(AddrResponseSchema)` to create a new message.
 */
const AddrResponseSchema = exports.AddrResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 8);

/**
 * @generated from message walletrpc.Account
 */

/**
 * Describes the message walletrpc.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
const AccountSchema = exports.AccountSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 9);

/**
 * @generated from message walletrpc.AddressProperty
 */

/**
 * Describes the message walletrpc.AddressProperty.
 * Use `create(AddressPropertySchema)` to create a new message.
 */
const AddressPropertySchema = exports.AddressPropertySchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 10);

/**
 * @generated from message walletrpc.AccountWithAddresses
 */

/**
 * Describes the message walletrpc.AccountWithAddresses.
 * Use `create(AccountWithAddressesSchema)` to create a new message.
 */
const AccountWithAddressesSchema = exports.AccountWithAddressesSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 11);

/**
 * @generated from message walletrpc.ListAccountsRequest
 */

/**
 * Describes the message walletrpc.ListAccountsRequest.
 * Use `create(ListAccountsRequestSchema)` to create a new message.
 */
const ListAccountsRequestSchema = exports.ListAccountsRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 12);

/**
 * @generated from message walletrpc.ListAccountsResponse
 */

/**
 * Describes the message walletrpc.ListAccountsResponse.
 * Use `create(ListAccountsResponseSchema)` to create a new message.
 */
const ListAccountsResponseSchema = exports.ListAccountsResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 13);

/**
 * @generated from message walletrpc.RequiredReserveRequest
 */

/**
 * Describes the message walletrpc.RequiredReserveRequest.
 * Use `create(RequiredReserveRequestSchema)` to create a new message.
 */
const RequiredReserveRequestSchema = exports.RequiredReserveRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 14);

/**
 * @generated from message walletrpc.RequiredReserveResponse
 */

/**
 * Describes the message walletrpc.RequiredReserveResponse.
 * Use `create(RequiredReserveResponseSchema)` to create a new message.
 */
const RequiredReserveResponseSchema = exports.RequiredReserveResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 15);

/**
 * @generated from message walletrpc.ListAddressesRequest
 */

/**
 * Describes the message walletrpc.ListAddressesRequest.
 * Use `create(ListAddressesRequestSchema)` to create a new message.
 */
const ListAddressesRequestSchema = exports.ListAddressesRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 16);

/**
 * @generated from message walletrpc.ListAddressesResponse
 */

/**
 * Describes the message walletrpc.ListAddressesResponse.
 * Use `create(ListAddressesResponseSchema)` to create a new message.
 */
const ListAddressesResponseSchema = exports.ListAddressesResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 17);

/**
 * @generated from message walletrpc.SignMessageWithAddrRequest
 */

/**
 * Describes the message walletrpc.SignMessageWithAddrRequest.
 * Use `create(SignMessageWithAddrRequestSchema)` to create a new message.
 */
const SignMessageWithAddrRequestSchema = exports.SignMessageWithAddrRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 18);

/**
 * @generated from message walletrpc.SignMessageWithAddrResponse
 */

/**
 * Describes the message walletrpc.SignMessageWithAddrResponse.
 * Use `create(SignMessageWithAddrResponseSchema)` to create a new message.
 */
const SignMessageWithAddrResponseSchema = exports.SignMessageWithAddrResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 19);

/**
 * @generated from message walletrpc.VerifyMessageWithAddrRequest
 */

/**
 * Describes the message walletrpc.VerifyMessageWithAddrRequest.
 * Use `create(VerifyMessageWithAddrRequestSchema)` to create a new message.
 */
const VerifyMessageWithAddrRequestSchema = exports.VerifyMessageWithAddrRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 20);

/**
 * @generated from message walletrpc.VerifyMessageWithAddrResponse
 */

/**
 * Describes the message walletrpc.VerifyMessageWithAddrResponse.
 * Use `create(VerifyMessageWithAddrResponseSchema)` to create a new message.
 */
const VerifyMessageWithAddrResponseSchema = exports.VerifyMessageWithAddrResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 21);

/**
 * @generated from message walletrpc.ImportAccountRequest
 */

/**
 * Describes the message walletrpc.ImportAccountRequest.
 * Use `create(ImportAccountRequestSchema)` to create a new message.
 */
const ImportAccountRequestSchema = exports.ImportAccountRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 22);

/**
 * @generated from message walletrpc.ImportAccountResponse
 */

/**
 * Describes the message walletrpc.ImportAccountResponse.
 * Use `create(ImportAccountResponseSchema)` to create a new message.
 */
const ImportAccountResponseSchema = exports.ImportAccountResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 23);

/**
 * @generated from message walletrpc.ImportPublicKeyRequest
 */

/**
 * Describes the message walletrpc.ImportPublicKeyRequest.
 * Use `create(ImportPublicKeyRequestSchema)` to create a new message.
 */
const ImportPublicKeyRequestSchema = exports.ImportPublicKeyRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 24);

/**
 * @generated from message walletrpc.ImportPublicKeyResponse
 */

/**
 * Describes the message walletrpc.ImportPublicKeyResponse.
 * Use `create(ImportPublicKeyResponseSchema)` to create a new message.
 */
const ImportPublicKeyResponseSchema = exports.ImportPublicKeyResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 25);

/**
 * @generated from message walletrpc.ImportTapscriptRequest
 */

/**
 * Describes the message walletrpc.ImportTapscriptRequest.
 * Use `create(ImportTapscriptRequestSchema)` to create a new message.
 */
const ImportTapscriptRequestSchema = exports.ImportTapscriptRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 26);

/**
 * @generated from message walletrpc.TapscriptFullTree
 */

/**
 * Describes the message walletrpc.TapscriptFullTree.
 * Use `create(TapscriptFullTreeSchema)` to create a new message.
 */
const TapscriptFullTreeSchema = exports.TapscriptFullTreeSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 27);

/**
 * @generated from message walletrpc.TapLeaf
 */

/**
 * Describes the message walletrpc.TapLeaf.
 * Use `create(TapLeafSchema)` to create a new message.
 */
const TapLeafSchema = exports.TapLeafSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 28);

/**
 * @generated from message walletrpc.TapscriptPartialReveal
 */

/**
 * Describes the message walletrpc.TapscriptPartialReveal.
 * Use `create(TapscriptPartialRevealSchema)` to create a new message.
 */
const TapscriptPartialRevealSchema = exports.TapscriptPartialRevealSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 29);

/**
 * @generated from message walletrpc.ImportTapscriptResponse
 */

/**
 * Describes the message walletrpc.ImportTapscriptResponse.
 * Use `create(ImportTapscriptResponseSchema)` to create a new message.
 */
const ImportTapscriptResponseSchema = exports.ImportTapscriptResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 30);

/**
 * @generated from message walletrpc.Transaction
 */

/**
 * Describes the message walletrpc.Transaction.
 * Use `create(TransactionSchema)` to create a new message.
 */
const TransactionSchema = exports.TransactionSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 31);

/**
 * @generated from message walletrpc.PublishResponse
 */

/**
 * Describes the message walletrpc.PublishResponse.
 * Use `create(PublishResponseSchema)` to create a new message.
 */
const PublishResponseSchema = exports.PublishResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 32);

/**
 * @generated from message walletrpc.SendOutputsRequest
 */

/**
 * Describes the message walletrpc.SendOutputsRequest.
 * Use `create(SendOutputsRequestSchema)` to create a new message.
 */
const SendOutputsRequestSchema = exports.SendOutputsRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 33);

/**
 * @generated from message walletrpc.SendOutputsResponse
 */

/**
 * Describes the message walletrpc.SendOutputsResponse.
 * Use `create(SendOutputsResponseSchema)` to create a new message.
 */
const SendOutputsResponseSchema = exports.SendOutputsResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 34);

/**
 * @generated from message walletrpc.EstimateFeeRequest
 */

/**
 * Describes the message walletrpc.EstimateFeeRequest.
 * Use `create(EstimateFeeRequestSchema)` to create a new message.
 */
const EstimateFeeRequestSchema = exports.EstimateFeeRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 35);

/**
 * @generated from message walletrpc.EstimateFeeResponse
 */

/**
 * Describes the message walletrpc.EstimateFeeResponse.
 * Use `create(EstimateFeeResponseSchema)` to create a new message.
 */
const EstimateFeeResponseSchema = exports.EstimateFeeResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 36);

/**
 * @generated from message walletrpc.PendingSweep
 */

/**
 * Describes the message walletrpc.PendingSweep.
 * Use `create(PendingSweepSchema)` to create a new message.
 */
const PendingSweepSchema = exports.PendingSweepSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 37);

/**
 * @generated from message walletrpc.PendingSweepsRequest
 */

/**
 * Describes the message walletrpc.PendingSweepsRequest.
 * Use `create(PendingSweepsRequestSchema)` to create a new message.
 */
const PendingSweepsRequestSchema = exports.PendingSweepsRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 38);

/**
 * @generated from message walletrpc.PendingSweepsResponse
 */

/**
 * Describes the message walletrpc.PendingSweepsResponse.
 * Use `create(PendingSweepsResponseSchema)` to create a new message.
 */
const PendingSweepsResponseSchema = exports.PendingSweepsResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 39);

/**
 * @generated from message walletrpc.BumpFeeRequest
 */

/**
 * Describes the message walletrpc.BumpFeeRequest.
 * Use `create(BumpFeeRequestSchema)` to create a new message.
 */
const BumpFeeRequestSchema = exports.BumpFeeRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 40);

/**
 * @generated from message walletrpc.BumpFeeResponse
 */

/**
 * Describes the message walletrpc.BumpFeeResponse.
 * Use `create(BumpFeeResponseSchema)` to create a new message.
 */
const BumpFeeResponseSchema = exports.BumpFeeResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 41);

/**
 * @generated from message walletrpc.ListSweepsRequest
 */

/**
 * Describes the message walletrpc.ListSweepsRequest.
 * Use `create(ListSweepsRequestSchema)` to create a new message.
 */
const ListSweepsRequestSchema = exports.ListSweepsRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 42);

/**
 * @generated from message walletrpc.ListSweepsResponse
 */

/**
 * Describes the message walletrpc.ListSweepsResponse.
 * Use `create(ListSweepsResponseSchema)` to create a new message.
 */
const ListSweepsResponseSchema = exports.ListSweepsResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 43);

/**
 * @generated from message walletrpc.ListSweepsResponse.TransactionIDs
 */

/**
 * Describes the message walletrpc.ListSweepsResponse.TransactionIDs.
 * Use `create(ListSweepsResponse_TransactionIDsSchema)` to create a new message.
 */
const ListSweepsResponse_TransactionIDsSchema = exports.ListSweepsResponse_TransactionIDsSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 43, 0);

/**
 * @generated from message walletrpc.LabelTransactionRequest
 */

/**
 * Describes the message walletrpc.LabelTransactionRequest.
 * Use `create(LabelTransactionRequestSchema)` to create a new message.
 */
const LabelTransactionRequestSchema = exports.LabelTransactionRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 44);

/**
 * @generated from message walletrpc.LabelTransactionResponse
 */

/**
 * Describes the message walletrpc.LabelTransactionResponse.
 * Use `create(LabelTransactionResponseSchema)` to create a new message.
 */
const LabelTransactionResponseSchema = exports.LabelTransactionResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 45);

/**
 * @generated from message walletrpc.FundPsbtRequest
 */

/**
 * Describes the message walletrpc.FundPsbtRequest.
 * Use `create(FundPsbtRequestSchema)` to create a new message.
 */
const FundPsbtRequestSchema = exports.FundPsbtRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 46);

/**
 * @generated from message walletrpc.FundPsbtResponse
 */

/**
 * Describes the message walletrpc.FundPsbtResponse.
 * Use `create(FundPsbtResponseSchema)` to create a new message.
 */
const FundPsbtResponseSchema = exports.FundPsbtResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 47);

/**
 * @generated from message walletrpc.TxTemplate
 */

/**
 * Describes the message walletrpc.TxTemplate.
 * Use `create(TxTemplateSchema)` to create a new message.
 */
const TxTemplateSchema = exports.TxTemplateSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 48);

/**
 * @generated from message walletrpc.UtxoLease
 */

/**
 * Describes the message walletrpc.UtxoLease.
 * Use `create(UtxoLeaseSchema)` to create a new message.
 */
const UtxoLeaseSchema = exports.UtxoLeaseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 49);

/**
 * @generated from message walletrpc.SignPsbtRequest
 */

/**
 * Describes the message walletrpc.SignPsbtRequest.
 * Use `create(SignPsbtRequestSchema)` to create a new message.
 */
const SignPsbtRequestSchema = exports.SignPsbtRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 50);

/**
 * @generated from message walletrpc.SignPsbtResponse
 */

/**
 * Describes the message walletrpc.SignPsbtResponse.
 * Use `create(SignPsbtResponseSchema)` to create a new message.
 */
const SignPsbtResponseSchema = exports.SignPsbtResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 51);

/**
 * @generated from message walletrpc.FinalizePsbtRequest
 */

/**
 * Describes the message walletrpc.FinalizePsbtRequest.
 * Use `create(FinalizePsbtRequestSchema)` to create a new message.
 */
const FinalizePsbtRequestSchema = exports.FinalizePsbtRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 52);

/**
 * @generated from message walletrpc.FinalizePsbtResponse
 */

/**
 * Describes the message walletrpc.FinalizePsbtResponse.
 * Use `create(FinalizePsbtResponseSchema)` to create a new message.
 */
const FinalizePsbtResponseSchema = exports.FinalizePsbtResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 53);

/**
 * @generated from message walletrpc.ListLeasesRequest
 */

/**
 * Describes the message walletrpc.ListLeasesRequest.
 * Use `create(ListLeasesRequestSchema)` to create a new message.
 */
const ListLeasesRequestSchema = exports.ListLeasesRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 54);

/**
 * @generated from message walletrpc.ListLeasesResponse
 */

/**
 * Describes the message walletrpc.ListLeasesResponse.
 * Use `create(ListLeasesResponseSchema)` to create a new message.
 */
const ListLeasesResponseSchema = exports.ListLeasesResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_walletrpc_walletkit, 55);

/**
 * @generated from enum walletrpc.AddressType
 */
let AddressType = exports.AddressType = /*#__PURE__*/function (AddressType) {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  AddressType[AddressType["UNKNOWN"] = 0] = "UNKNOWN";
  /**
   * @generated from enum value: WITNESS_PUBKEY_HASH = 1;
   */
  AddressType[AddressType["WITNESS_PUBKEY_HASH"] = 1] = "WITNESS_PUBKEY_HASH";
  /**
   * @generated from enum value: NESTED_WITNESS_PUBKEY_HASH = 2;
   */
  AddressType[AddressType["NESTED_WITNESS_PUBKEY_HASH"] = 2] = "NESTED_WITNESS_PUBKEY_HASH";
  /**
   * @generated from enum value: HYBRID_NESTED_WITNESS_PUBKEY_HASH = 3;
   */
  AddressType[AddressType["HYBRID_NESTED_WITNESS_PUBKEY_HASH"] = 3] = "HYBRID_NESTED_WITNESS_PUBKEY_HASH";
  /**
   * @generated from enum value: TAPROOT_PUBKEY = 4;
   */
  AddressType[AddressType["TAPROOT_PUBKEY"] = 4] = "TAPROOT_PUBKEY";
  return AddressType;
}({});
/**
 * Describes the enum walletrpc.AddressType.
 */
const AddressTypeSchema = exports.AddressTypeSchema = /*@__PURE__*/
(0, _codegenv.enumDesc)(file_walletrpc_walletkit, 0);

/**
 * @generated from enum walletrpc.WitnessType
 */
let WitnessType = exports.WitnessType = /*#__PURE__*/function (WitnessType) {
  /**
   * @generated from enum value: UNKNOWN_WITNESS = 0;
   */
  WitnessType[WitnessType["UNKNOWN_WITNESS"] = 0] = "UNKNOWN_WITNESS";
  /**
   *
   * A witness that allows us to spend the output of a commitment transaction
   * after a relative lock-time lockout.
   *
   * @generated from enum value: COMMITMENT_TIME_LOCK = 1;
   */
  WitnessType[WitnessType["COMMITMENT_TIME_LOCK"] = 1] = "COMMITMENT_TIME_LOCK";
  /**
   *
   * A witness that allows us to spend a settled no-delay output immediately on a
   * counterparty's commitment transaction.
   *
   * @generated from enum value: COMMITMENT_NO_DELAY = 2;
   */
  WitnessType[WitnessType["COMMITMENT_NO_DELAY"] = 2] = "COMMITMENT_NO_DELAY";
  /**
   *
   * A witness that allows us to sweep the settled output of a malicious
   * counterparty's who broadcasts a revoked commitment transaction.
   *
   * @generated from enum value: COMMITMENT_REVOKE = 3;
   */
  WitnessType[WitnessType["COMMITMENT_REVOKE"] = 3] = "COMMITMENT_REVOKE";
  /**
   *
   * A witness that allows us to sweep an HTLC which we offered to the remote
   * party in the case that they broadcast a revoked commitment state.
   *
   * @generated from enum value: HTLC_OFFERED_REVOKE = 4;
   */
  WitnessType[WitnessType["HTLC_OFFERED_REVOKE"] = 4] = "HTLC_OFFERED_REVOKE";
  /**
   *
   * A witness that allows us to sweep an HTLC output sent to us in the case that
   * the remote party broadcasts a revoked commitment state.
   *
   * @generated from enum value: HTLC_ACCEPTED_REVOKE = 5;
   */
  WitnessType[WitnessType["HTLC_ACCEPTED_REVOKE"] = 5] = "HTLC_ACCEPTED_REVOKE";
  /**
   *
   * A witness that allows us to sweep an HTLC output that we extended to a
   * party, but was never fulfilled.  This HTLC output isn't directly on the
   * commitment transaction, but is the result of a confirmed second-level HTLC
   * transaction. As a result, we can only spend this after a CSV delay.
   *
   * @generated from enum value: HTLC_OFFERED_TIMEOUT_SECOND_LEVEL = 6;
   */
  WitnessType[WitnessType["HTLC_OFFERED_TIMEOUT_SECOND_LEVEL"] = 6] = "HTLC_OFFERED_TIMEOUT_SECOND_LEVEL";
  /**
   *
   * A witness that allows us to sweep an HTLC output that was offered to us, and
   * for which we have a payment preimage. This HTLC output isn't directly on our
   * commitment transaction, but is the result of confirmed second-level HTLC
   * transaction. As a result, we can only spend this after a CSV delay.
   *
   * @generated from enum value: HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL = 7;
   */
  WitnessType[WitnessType["HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL"] = 7] = "HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL";
  /**
   *
   * A witness that allows us to sweep an HTLC that we offered to the remote
   * party which lies in the commitment transaction of the remote party. We can
   * spend this output after the absolute CLTV timeout of the HTLC as passed.
   *
   * @generated from enum value: HTLC_OFFERED_REMOTE_TIMEOUT = 8;
   */
  WitnessType[WitnessType["HTLC_OFFERED_REMOTE_TIMEOUT"] = 8] = "HTLC_OFFERED_REMOTE_TIMEOUT";
  /**
   *
   * A witness that allows us to sweep an HTLC that was offered to us by the
   * remote party. We use this witness in the case that the remote party goes to
   * chain, and we know the pre-image to the HTLC. We can sweep this without any
   * additional timeout.
   *
   * @generated from enum value: HTLC_ACCEPTED_REMOTE_SUCCESS = 9;
   */
  WitnessType[WitnessType["HTLC_ACCEPTED_REMOTE_SUCCESS"] = 9] = "HTLC_ACCEPTED_REMOTE_SUCCESS";
  /**
   *
   * A witness that allows us to sweep an HTLC from the remote party's commitment
   * transaction in the case that the broadcast a revoked commitment, but then
   * also immediately attempt to go to the second level to claim the HTLC.
   *
   * @generated from enum value: HTLC_SECOND_LEVEL_REVOKE = 10;
   */
  WitnessType[WitnessType["HTLC_SECOND_LEVEL_REVOKE"] = 10] = "HTLC_SECOND_LEVEL_REVOKE";
  /**
   *
   * A witness type that allows us to spend a regular p2wkh output that's sent to
   * an output which is under complete control of the backing wallet.
   *
   * @generated from enum value: WITNESS_KEY_HASH = 11;
   */
  WitnessType[WitnessType["WITNESS_KEY_HASH"] = 11] = "WITNESS_KEY_HASH";
  /**
   *
   * A witness type that allows us to sweep an output that sends to a nested P2SH
   * script that pays to a key solely under our control.
   *
   * @generated from enum value: NESTED_WITNESS_KEY_HASH = 12;
   */
  WitnessType[WitnessType["NESTED_WITNESS_KEY_HASH"] = 12] = "NESTED_WITNESS_KEY_HASH";
  /**
   *
   * A witness type that allows us to spend our anchor on the commitment
   * transaction.
   *
   * @generated from enum value: COMMITMENT_ANCHOR = 13;
   */
  WitnessType[WitnessType["COMMITMENT_ANCHOR"] = 13] = "COMMITMENT_ANCHOR";
  /**
   *
   * A witness type that is similar to the COMMITMENT_NO_DELAY type,
   * but it omits the tweak that randomizes the key we need to
   * spend with a channel peer supplied set of randomness.
   *
   * @generated from enum value: COMMITMENT_NO_DELAY_TWEAKLESS = 14;
   */
  WitnessType[WitnessType["COMMITMENT_NO_DELAY_TWEAKLESS"] = 14] = "COMMITMENT_NO_DELAY_TWEAKLESS";
  /**
   *
   * A witness type that allows us to spend our output on the counterparty's
   * commitment transaction after a confirmation.
   *
   * @generated from enum value: COMMITMENT_TO_REMOTE_CONFIRMED = 15;
   */
  WitnessType[WitnessType["COMMITMENT_TO_REMOTE_CONFIRMED"] = 15] = "COMMITMENT_TO_REMOTE_CONFIRMED";
  /**
   *
   * A witness type that allows us to sweep an HTLC output that we extended
   * to a party, but was never fulfilled. This _is_ the HTLC output directly
   * on our commitment transaction, and the input to the second-level HTLC
   * timeout transaction. It can only be spent after CLTV expiry, and
   * commitment confirmation.
   *
   * @generated from enum value: HTLC_OFFERED_TIMEOUT_SECOND_LEVEL_INPUT_CONFIRMED = 16;
   */
  WitnessType[WitnessType["HTLC_OFFERED_TIMEOUT_SECOND_LEVEL_INPUT_CONFIRMED"] = 16] = "HTLC_OFFERED_TIMEOUT_SECOND_LEVEL_INPUT_CONFIRMED";
  /**
   *
   * A witness type that allows us to sweep an HTLC output that was offered
   * to us, and for which we have a payment preimage. This _is_ the HTLC
   * output directly on our commitment transaction, and the input to the
   * second-level HTLC success transaction. It can only be spent after the
   * commitment has confirmed.
   *
   * @generated from enum value: HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL_INPUT_CONFIRMED = 17;
   */
  WitnessType[WitnessType["HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL_INPUT_CONFIRMED"] = 17] = "HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL_INPUT_CONFIRMED";
  /**
   *
   * A witness type that allows us to spend our output on our local
   * commitment transaction after a relative and absolute lock-time lockout as
   * part of the script enforced lease commitment type.
   *
   * @generated from enum value: LEASE_COMMITMENT_TIME_LOCK = 18;
   */
  WitnessType[WitnessType["LEASE_COMMITMENT_TIME_LOCK"] = 18] = "LEASE_COMMITMENT_TIME_LOCK";
  /**
   *
   * A witness type that allows us to spend our output on the counterparty's
   * commitment transaction after a confirmation and absolute locktime as part
   * of the script enforced lease commitment type.
   *
   * @generated from enum value: LEASE_COMMITMENT_TO_REMOTE_CONFIRMED = 19;
   */
  WitnessType[WitnessType["LEASE_COMMITMENT_TO_REMOTE_CONFIRMED"] = 19] = "LEASE_COMMITMENT_TO_REMOTE_CONFIRMED";
  /**
   *
   * A witness type that allows us to sweep an HTLC output that we extended
   * to a party, but was never fulfilled. This HTLC output isn't directly on
   * the commitment transaction, but is the result of a confirmed second-level
   * HTLC transaction. As a result, we can only spend this after a CSV delay
   * and CLTV locktime as part of the script enforced lease commitment type.
   *
   * @generated from enum value: LEASE_HTLC_OFFERED_TIMEOUT_SECOND_LEVEL = 20;
   */
  WitnessType[WitnessType["LEASE_HTLC_OFFERED_TIMEOUT_SECOND_LEVEL"] = 20] = "LEASE_HTLC_OFFERED_TIMEOUT_SECOND_LEVEL";
  /**
   *
   * A witness type that allows us to sweep an HTLC output that was offered
   * to us, and for which we have a payment preimage. This HTLC output isn't
   * directly on our commitment transaction, but is the result of confirmed
   * second-level HTLC transaction. As a result, we can only spend this after
   * a CSV delay and CLTV locktime as part of the script enforced lease
   * commitment type.
   *
   * @generated from enum value: LEASE_HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL = 21;
   */
  WitnessType[WitnessType["LEASE_HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL"] = 21] = "LEASE_HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL";
  /**
   *
   * A witness type that allows us to spend a regular p2tr output that's sent
   * to an output which is under complete control of the backing wallet.
   *
   * @generated from enum value: TAPROOT_PUB_KEY_SPEND = 22;
   */
  WitnessType[WitnessType["TAPROOT_PUB_KEY_SPEND"] = 22] = "TAPROOT_PUB_KEY_SPEND";
  return WitnessType;
}({});
/**
 * Describes the enum walletrpc.WitnessType.
 */
const WitnessTypeSchema = exports.WitnessTypeSchema = /*@__PURE__*/
(0, _codegenv.enumDesc)(file_walletrpc_walletkit, 1);

/**
 * The possible change address types for default accounts and single imported
 * public keys. By default, P2WPKH will be used. We don't provide the
 * possibility to choose P2PKH as it is a legacy key scope, nor NP2WPKH as
 * no key scope permits to do so. For custom accounts, no change type should
 * be provided as the coin selection key scope will always be used to generate
 * the change address.
 *
 * @generated from enum walletrpc.ChangeAddressType
 */
let ChangeAddressType = exports.ChangeAddressType = /*#__PURE__*/function (ChangeAddressType) {
  /**
   * CHANGE_ADDRESS_TYPE_UNSPECIFIED indicates that no change address type is
   * provided. We will then use P2WPKH address type for change (BIP0084 key
   * scope).
   *
   * @generated from enum value: CHANGE_ADDRESS_TYPE_UNSPECIFIED = 0;
   */
  ChangeAddressType[ChangeAddressType["UNSPECIFIED"] = 0] = "UNSPECIFIED";
  /**
   * CHANGE_ADDRESS_TYPE_P2TR indicates to use P2TR address for change output
   * (BIP0086 key scope).
   *
   * @generated from enum value: CHANGE_ADDRESS_TYPE_P2TR = 1;
   */
  ChangeAddressType[ChangeAddressType["P2TR"] = 1] = "P2TR";
  /**
   * ChangeAddressType_CHANGE_ADDRESS_TYPE_MWEB indicates to use MWEB address
   * for change output.
   *
   * @generated from enum value: CHANGE_ADDRESS_TYPE_MWEB = 2;
   */
  ChangeAddressType[ChangeAddressType["MWEB"] = 2] = "MWEB";
  return ChangeAddressType;
}({});
/**
 * Describes the enum walletrpc.ChangeAddressType.
 */
const ChangeAddressTypeSchema = exports.ChangeAddressTypeSchema = /*@__PURE__*/
(0, _codegenv.enumDesc)(file_walletrpc_walletkit, 2);

/**
 * WalletKit is a service that gives access to the core functionalities of the
 * daemon's wallet.
 *
 * @generated from service walletrpc.WalletKit
 */
const WalletKit = exports.WalletKit = /*@__PURE__*/
(0, _codegenv.serviceDesc)(file_walletrpc_walletkit, 0);
//# sourceMappingURL=walletkit_pb.js.map