"use strict";

// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file lnclipb/lncli.proto (package lnclipb, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_verrpc_verrpc } from "../verrpc/verrpc_pb.js";
/**
 * Describes the file lnclipb/lncli.proto.
 */
export const file_lnclipb_lncli = /*@__PURE__*/
fileDesc("ChNsbmNsaXBiL2xuY2xpLnByb3RvEgdsbmNsaXBiIk8KD1ZlcnNpb25SZXNwb25zZRIeCgVsbmNsaRgBIAEoCzIPLnZlcnJwYy5WZXJzaW9uEhwKA2xuZBgCIAEoCzIPLnZlcnJwYy5WZXJzaW9uQidaJWdpdGh1Yi5jb20vbHRjc3VpdGUvbG5kL2xucnBjL2xuY2xpcGJiBnByb3RvMw", [file_verrpc_verrpc]);

/**
 * @generated from message lnclipb.VersionResponse
 */

/**
 * Describes the message lnclipb.VersionResponse.
 * Use `create(VersionResponseSchema)` to create a new message.
 */
export const VersionResponseSchema = /*@__PURE__*/
messageDesc(file_lnclipb_lncli, 0);
//# sourceMappingURL=lncli_pb.js.map